spring:
  datasource:
      name: phoenix-hbase
      url: jdbc:phoenix:hbase:2181
      driver-class-name: org.apache.phoenix.jdbc.PhoenixDriver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: com.ruesga.phoenix.dialect.PhoenixDialect
        hbm2ddl.auto: none
